<div class="row">
  <div class="span12">
    <form class="form-horizontal well centered_form" method="post" action="/reset/password">
      <input type="hidden" name="key" value="<?php echo $this->key ?>">
      <?php echo $this->token ?>
      <fieldset>
        <legend>Reset Password</legend>
        <div class="control-group">
          <label class="control-label" for="email">Email address</label>
          <div class="controls">
            <input class="input-xlarge focused" id="email" type="text" name="email" value="" placeholder="Email">
            <span class="help-inline">What's your email address?</span>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="password">Password</label>
          <div class="controls">
            <input class="input-xlarge focused" id="password" type="password" name="password" value="" placeholder="Password">
            <span class="help-inline">6 characters or more! Be tricky.</span>
          </div>
        </div>
        <div class="form-actions">
          <button type="submit" class="btn btn-primary">Submit</button>
          <button class="btn">Cancel</button>
        </div>
      </fieldset>
    </form>
  </div>
</div>