<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title><?php echo APPLICATION_NAME ?> - Email Verification</title>
<style>
body {
	background-color:#d7e1e5;
	font-size:14px;
	color:#394852;
	line-height:150%;
	font-family: Arial, sans-serif;
}
</style>
</head>
<body>

<h1>Hello <?php echo $this->name ?></h1>

<p>Please click the link below to verify your email address change on the <?php echo APPLICATION_NAME ?> web site.</p>

<p><a href="<?php echo $this->server ?>/account/verify/id/<?php echo $this->id ?>/email/<?php echo $this->email ?>">Click here to verify your email address account change.</a></p>

<p>Or click here,</p>

<p><a href="<?php echo $this->server ?>/account/verify/id/<?php echo $this->id ?>/email/<?php echo $this->email ?>"><?php echo $this->server ?>/account/verify/id/<?php echo $this->id ?>/email/<?php echo $this->email ?></a></p>

<p>Sincerely.<br /><br />
<?php echo APPLICATION_NAME ?> Staff</p>

</body>
</html>