<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title><?php echo APPLICATION_NAME ?> Registration Conformation</title>
<style>
body {
	background-color:#d7e1e5;
	font-size:14px;
	color:#394852;
	line-height:150%;
	font-family: Arial, sans-serif;
}
</style>
</head>
<body>

<h1>Hello <?php echo $this->name ?></h1>

<p>Thank you for registering with <?php echo APPLICATION_NAME ?></p>

<p>To confirm your email address with us please click on one of the following links.</p>

<p><a href="<?php echo $this->server ?>/register/email/key/<?php echo $this->key ?>">Click here to confirm your email address.</a></p>

<p>Or click here,</p>

<p><a href="<?php echo $this->server ?>/register/email/key/<?php echo $this->key ?>"><?php echo $this->server ?>/login/reset/key/<?php echo $this->key ?></a></p>

<p>Sincerely.<br /><br />
<?php echo APPLICATION_NAME ?> Staff</p>

</body>
</html>