<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>My Quick Start Web Site - Reset Password</title>
<style>
body {
	background-color:#d7e1e5;
	font-size:14px;
	color:#394852;
	line-height:150%;
	font-family: Arial, sans-serif;
}
</style>
</head>
<body>

<h1>Hello <?php echo $this->customer_name ?></h1>

<p>If you are not <?php echo $this->customer_name ?>, please disregard this message. If you did not request to change or reset your password disregard this message. If you feel this message is in error please contact us by telephone.</p>

<p>If you wish to reset your password on the Quick Start web site please click one of the links below and follow the instructions.</p>

<p><a href="<?php echo $this->server ?>/reset/password/key/<?php echo $this->customer_key ?>">Click here to reset your password on the Quick Start Web Site</a></p>

<p>Or click here,</p>

<p><a href="<?php echo $this->server ?>/reset/password/key/<?php echo $this->customer_key ?>"><?php echo $this->server ?>/login/reset/key/<?php echo $this->customer_key ?></a></p>

<p>Sincerely.<br /><br />
<?php echo APPLICATION_NAME ?> Staff</p>

</body>
</html>