<div style="margin-top:30px;"></div>
<?php if (count($this->messages)): ?>
<?php if ($this->messageType == 'success'): ?>
<div class="alert alert-success fade in" style="width:55%;">
  <a class="close" data-dismiss="alert" href="#">x</a>
  <strong>Completed successfully!</strong> 
  <br/><br/>
  <?php foreach($this->messages as $message): ?>
  <p><?php echo $message ?></p>
  <?php endforeach; ?>
  <br/>
  <p><a class="btn" href="/<?php echo $this->moduleName; ?>/<?php echo $this->controllerName; ?>">Return to menu.</a></p>
</div>
<?php elseif ($this->messageType == 'error'): ?>
<div class="alert alert-block alert-error fade in" style="width:55%;">
  <a class="close" data-dismiss="alert" href="#">x</a>
  <h4 class="alert-heading" style="margin-top:-5px;">Oh snap! You got an error!</h4>
  <br/>
  <?php foreach($this->messages as $message): ?>
  <p><?php echo $message ?></p>
  <?php endforeach; ?>
  <br/>
  <p><a class="btn btn-danger" href="mailto:admin@website.com">Notifiy Administrator</a> <a class="btn" href="/<?php echo $this->moduleName; ?>/<?php echo $this->controllerName; ?>">Return to menu.</a></p>
</div>
<?php elseif ($this->messageType == 'notice'): ?>
<div class="alert alert-block alert-info fade in" style="width:55%;">
  <a class="close" data-dismiss="alert" href="#">x</a>
  <h4 class="alert-heading" style="margin-top:-5px;">System information</h4>
  <br/>
  <?php foreach($this->messages as $message): ?>
  <p><?php echo $message ?></p>
  <?php endforeach; ?>
  <br/>
  <p><a class="btn" href="/<?php echo $this->moduleName; ?>/<?php echo $this->controllerName; ?>">Return to menu.</a></p>
</div>
<?php endif; ?>
<?php endif; ?>