<div class="page-header">
  <h1>Zend Framework Rest Controller Testing</h1>
  <p>A simple quick start application created to explorer and learn how to use controllers that extend Zend_Rest_Controller.</p>
</div>

<div class="row">
  <div class="span12">
    <form class="form-horizontal well centered_form" method="post" action="/register">
      <?php echo $this->token ?>
      <fieldset>
        <legend>Register</legend>
        <div class="control-group">
          <label class="control-label" for="name">Full name</label>
          <div class="controls">
            <input class="input-xlarge focused" id="name" type="text" name="name" value="" placeholder="Full name">
            <span class="help-inline">Enter your first and last name.</span>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="email">Email address</label>
          <div class="controls">
            <input class="input-xlarge focused" id="email" type="text" name="email" value="" placeholder="Email">
            <span class="help-inline">What's your email address?</span>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="password">Password</label>
          <div class="controls">
            <input class="input-xlarge focused" id="password" type="password" name="password" value="" placeholder="Password">
            <span class="help-inline">6 characters or more! Be tricky.</span>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="username">Username</label>
          <div class="controls">
            <input class="input-xlarge focused" id="username" type="text" name="username" value="" placeholder="Username">
            <span class="help-inline">Don't worry you can change it later.</span>
          </div>
        </div>
        <div class="form-actions">
          <button type="submit" class="btn btn-primary">Submit</button>
          <button class="btn">Cancel</button>
        </div>
        Have an account? <a href="/login" title="Sing in">Sign in</a>
      </fieldset>
    </form>
  </div>
</div>