<h1>RSS at Zend</h1> 
 
<h2>What is an RSS feed?</h2> 
 
<div class="content-col"><p><strong><img align="left" class="passport-img" alt="RSS" src="http://static.zend.com/topics/rss2.png" />RSS</strong> (Really Simple Syndication) is a family of web feed formats used to publish frequently updated content such as blog entries, news headlines or podcasts. An RSS document contains either a summary of content from an associated web site or the full text. RSS makes it possible for people to keep up with their favorite web sites in an automated manner that's easier than checking them manually.</p> 
<p>RSS content can be read using software called a "feed reader" or an "aggregator." The user subscribes to a feed by entering the feed's link into the reader or by clicking an RSS icon in a browser that initiates the subscription process. The reader checks the user's subscribed feeds regularly for new content, downloading any updates that it finds.</p> 
<p><font size="1">Source: <a target="_blank" href="http://wikipedia.com">wikipedia.com</a></font><br /></p></div> 
 
<h2>Subscribe to our RSS feeds</h2> 
 
<div class="content-col">
  <a href="/en/company/news/press/feed">News RSS feed</a><br />
  <a href="/en/company/news/news-links/feed">Zend in the News RSS feed</a><br />
  <a href="/en/company/news/event/feed">Events RSS feed</a><br />
  <a href="/en/company/news/newsletter/feed">Newsletter RSS feed</a>
</div> 
