<div style="clear: both;" /></div>
<h1>SQL Statements</h1>
<table>
  <thead>
    <tr>
      <th style="text-align: center;">Count</th>
      <th>&nbsp;Raw SQL Statement</th>
      <th style="text-align: center;">Time</th>
    </tr>
  </thead>
  <tbody>
  	<?php foreach($this->queries as $out): ?>
    <tr>
      <td style="text-align: center; vertical-align: top;">#<?= $out['count'] ?>.</td>
      <td><strong><?= $out['query'] ?></strong></td>
      <td><i><?= $out['seconds'] ?> ms.</i></td>
    </tr>
    <?php endforeach; ?>
  </tbody>
</table>
<h1>RDBMS Statistics</h1>
<table style="width: 40%">
  <thead>
    <tr>
      <th style="width: 80%">&nbsp;Statistic</th>
      <th style="text-align: center; width: 20%">Value</th>
    </tr>
  </thead>	
  <tbody>
    <tr>
      <td><strong>Total queries</strong>.</td>
      <td>#<?= $this->query_count ?>.</td>
    </tr>
    <tr>
      <td><strong>Average query length</strong>.</td>
      <td><i><?= $this->query_length ?> ms.</i></td>
    </tr>
    <tr>
      <td><strong>Queries per second</strong>.</td>
      <td><i><?= $this->queries_per_second ?> ms.</i></td>
    </tr>
    <tr>
      <td><strong>Longest query length</strong>.</td>
      <td><i><?= $this->longest_query_length ?> ms.</i></td>
    </tr>
    <tr>
      <td><strong>Longest query</strong>.</td>
      <td><i><?= $this->longest_query ?> ms.</i></td>
    </tr>
  </tbody>
</table>
<br />