<div class="page-header">
  <h1>Haphazard - Zend Framework Development</h1>
  <p>A simple quick start application created to explorer and learn the basics of Zend Framework</p>
</div>

<div style="text-align:left;margin:5px;">
  <?php echo $this->paginationControl($this->data, 'Jumping', 'gridpage.phtml'); ?>
</div>

<form method="post" id="form" action="/admin/entries/edit">
<?= $this->formHidden('id') ?>
<?= $this->formHidden('parent_id', $this->parent_id) ?>
<?= $this->formHidden('listing', true) ?>
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th style="width: 6%; text-align: center;">Edit</th>
      <th style="width: 24%;">&nbsp;Title</th>
      <th style="width: 8%; text-align: center;">Type</th>
      <th style="width: 10%; text-align: center;">User</th>
      <th style="width: 8%; text-align: center;">Comments</th>
      <th style="width: 8%; text-align: center;">Draft</th>
      <th style="width: 10%; text-align: center;">Trackbacks</th>
      <th style="width: 8%; text-align: center;">Approved</th>
      <th style="width: 8%; text-align: center;">Del</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td colspan="9"><a href="/admin/entries">Categories</a> <?php foreach($this->navdata as $nav): ?> <i class="icon-arrow-right" style="margin-top:1px;"></i> <a href="/admin/entries/index/parent_id/<?= $nav->id ?>"><?= $nav->title ?></a><?php endforeach; ?></td>
    </tr>
    <?php if(sizeof($this->data)): ?>
    <?php foreach($this->data as $row): ?>
    <tr>
      <td style="text-align: center;"><?= $this->formSubmit('submit', 'Edit', array('onclick'=>"this.form.id.value='{$row->id}'", "class"=>"btn","title"=>"Edit")) ?></td>
      <td><a href="/admin/entries/index/parent_id/<?= substr($row->id,0,80) ?>" title="<?= new Zend_Date($row->created); ?>/<?= new Zend_Date($row->modified); ?>"><?= $row->title ?></a></td>
      <td style="text-align: center;"><?php if($row->parent_id): ?>Entry<?php else: ?>Category<?php endif; ?></td>
      <td style="text-align: center;"><a href="/admin/users/edit/id/<?= $row->user_id; ?>" title="<?= $row->email; ?>"><?= $row->author; ?></a></td>
      <td style="text-align: center;"><?php if($row->comments): ?>Yes<?php else: ?>No<?php endif; ?></td>
      <td style="text-align: center;"><?php if($row->draft): ?>Yes<?php else: ?>No<?php endif; ?></td>
      <td style="text-align: center;"><?php if($row->trackbacks): ?>Yes<?php else: ?>No<?php endif; ?></td>
      <td style="text-align: center;"><?php if($row->approved): ?>Yes<?php else: ?>No<?php endif; ?></td>
      <td style="text-align: center;"><a href="/admin/entries/delete/id/<?= $row->id ?>" onclick="return confirm('Are you sure you wish to delete selected entries');">Delete</a></td>
    </tr>
    <?php endforeach; ?>
    <?php endif; ?>
    <tr>
      <td colspan="9"><a class="button" href="/admin/entries/create/parent_id/<?= $this->parent_id ?>"><?php if($this->parent_id):?>Create New Blog Entry<?php else: ?>Create New Category<?php endif; ?></a></td>
    </tr>
  </tbody>
</table>
</form>