<div class="page-header">
  <h1>Haphazard - Zend Framework Development</h1>
  <p>A simple quick start application created to explorer and learn the basics of Zend Framework</p>
</div>

<div style="text-align:left;margin:5px;">
  <?php echo $this->paginationControl($this->rows, 'Jumping', 'gridpage.phtml'); ?>
</div>

<a class="button2" href="/admin/polls/create" title="Create New Poll">Create New Poll</a>

<form method="post" id="form" action="/admin/polls/edit">
  <?= $this->formHidden('id') ?>
  <input type="hidden" name="listing" value="1">
  <table class="table table-striped table-bordered table-condensed">
    <thead>
      <tr>
        <th style="width: 5%; text-align: center;">Edit</th>
        <th style="width: 30%;">&nbsp;Title</th>
        <th style="width: 7%; text-align: center;">Start</th>
        <th style="width: 7%; text-align: center;">Expires</th>
        <th style="width: 7%; text-align: center;">Interval</th>
        <th style="width: 5%; text-align: center;">Enabled</th>
        <th style="width: 5%; text-align: center;">VoteFirst</th>
        <th style="width: 5%; text-align: center;">Confidential</th>
        <th style="width: 5%; text-align: center;">IP</th>
        <th style="width: 5%; text-align: center;">Cookie</th>
        <th style="width: 15%; text-align: center;">Created</th>
        <th style="width: 5%; text-align: center;">Del</th>
      </tr>
    </thead>
    <tbody>
      <?php if(sizeof($this->rows)): ?>
      <?php foreach($this->rows as $row): ?>
      <?php $colour = $this->cycle(array("#baccd9","#cadceb"))->next(); ?>
      <tr>
        <td style="text-align: center;"><?= $this->formSubmit('submit', 'Edit', array('onclick' => "this.form.id.value='{$row->id}'", "class" => "btn", "title" => 'Edit')) ?></td>
        <td><strong><a href="/admin/polls/edit/id/<?= $row->id ?>" title="Edit Poll"><?= $row->title ?></a></strong><br /><?= $row->description; ?></td>
        <td style="text-align: center;"><strong><?= $row->starts ?></strong></td>
        <td style="text-align: center;"><strong><?= $row->expires ?></strong></td>
        <td style="text-align: center;"><strong><?= $row->interval ?></strong></td>
        <td style="text-align: center;"><strong><?php if($row->enabled): ?>Yes<?php else: ?>No<?php endif; ?></strong></td>
        <td style="text-align: center;"><strong><?php if($row->votefirst): ?>Yes<?php else: ?>No<?php endif; ?></strong></td>
        <td style="text-align: center;"><strong><?php if($row->confidential): ?>Yes<?php else: ?>No<?php endif; ?></strong></td>
        <td style="text-align: center;"><strong><?php if($row->ip): ?>Yes<?php else: ?>No<?php endif; ?></strong></td>
        <td style="text-align: center;"><strong><?php if($row->cookie): ?>Yes<?php else: ?>No<?php endif; ?></strong></td>
        <td style="text-align: center;"><strong><?= new Zend_Date($row->created); ?></strong></td>
        <td style="text-align: center;"><strong><a class="button2" href="/admin/polls/delete/id/<?= $row->id ?>" title="Delete Poll" onclick="return confirm('Are you sure you wish to delete selected entries');">#</a></strong></td>
      </tr>
      <?php endforeach; ?>
      <?php endif; ?>
    </tbody>
  </table>
</form>