<div id="archives">
  <div class="title">
    <h2>Weblog Archives</h2>
  </div>
  <div class="list">
    <ul>
      <?php foreach($this->archives as $data): ?>
      <?php if($data['count'] || !$data['count']): ?>
      <li <?php if($data['count']): ?>class="active"<?php endif; ?>><a href="/archives/<?= $data['link'] ?>" title="View <?= $data['title'] ?>"><?php if($data['count']): ?>&nbsp;&nbsp;&nbsp;<?php endif; ?><?= $data['title'] ?></a><?= $data['count'] ?>&nbsp;&nbsp;</li>
      <?php endif; ?>
      <?php endforeach; ?>
    </ul>
  </div>
</div>
