<div style="height:auto; padding: 15px 5px 10px 15px;">
<table style="width:200px;">
  <thead>
    <tr>
      <th colspan="1" style="text-align:left; padding-left:4px;"><?php echo $this->previous_link ?></th>
      <th colspan="5"><?php echo $this->month_name ?>-<?php echo $this->year_name ?></th>
      <th colspan="1" style="text-align:right; padding-right:4px;"><?php echo $this->next_link ?></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="days">S</td>
      <td class="days">M</td>
      <td class="days">T</td>
      <td class="days">W</td>
      <td class="days">T</td>
      <td class="days">F</td>
      <td class="days">S</td>
    </tr>
    <?php foreach($this->weeks as $week): ?>
    <tr>
      <?php foreach($week as $day): ?>
      <td class="<?php echo $day['class'] ?>"><?php echo $day['link'] ?></td>
      <?php endforeach; ?>
    </tr>
    <?php endforeach; ?>
  </tbody>
</table>
</div>
