<div id="bottom">
  <h2>Tom Shaw Development</h2>
  <div class="column1">
    <h3>Latest Tweets</h3>
    <ul>
    	<?php foreach($this->tweets as $tweet): ?> 
        <li><span class="headline"><a href="http://twitter.com/tomshaws"><?= $tweet['created'] ?></a></span>
          <div><?= $tweet['text'] ?></div>
        </li>
        <?php endforeach; ?>
    </ul>
  </div>
  <div class="column2">
    <h3>Newest Links</h3>
    <ul>
      <li><span class="headline"><a href="http://www.jqtouch.com/">jQuery plugin for mobile development.</a></span>
        <div>A jQuery plugin for mobile web development on the iPhone, Android, Palm Pre, and other forward-thinking devices.</div>
      </li>
      <li><span class="headline"><a href="/blog/dev/how-to-debug-in-php/">How to Debug in PHP</a></span>
        <div>Nobody enjoys the process of debugging their code. If you want to build killer web apps though, it's vital that you understand the process thoroughly.</div>
      </li>
      <li><span class="headline"><a href="/blog/dev/how-to-debug-in-php/">How to Debug in PHP</a></span>
        <div>Nobody enjoys the process of debugging their code. If you want to build killer web apps though, it's vital that you understand the process thoroughly.</div>
      </li>
      <li><span class="headline"><a href="/blog/dev/how-to-debug-in-php/">How to Debug in PHP</a></span>
        <div>Nobody enjoys the process of debugging their code. If you want to build killer web apps though, it's vital that you understand the process thoroughly.</div>
      </li>
    </ul>
  </div>
  <div class="column3">
    <h3>Current Topics</h3>
    <ul>
      <li><span class="headline"><a href="http://www.jqtouch.com/">jQuery plugin for mobile development.</a></span>
        <div>A jQuery plugin for mobile web development on the iPhone, Android, Palm Pre, and other forward-thinking devices.</div>
      </li>
      <li><span class="headline"><a href="/blog/dev/how-to-debug-in-php/">How to Debug in PHP</a></span>
        <div>Nobody enjoys the process of debugging their code. If you want to build killer web apps though, it's vital that you understand the process thoroughly.</div>
      </li>
      <li><span class="headline"><a href="/blog/dev/how-to-debug-in-php/">How to Debug in PHP</a></span>
        <div>Nobody enjoys the process of debugging their code. If you want to build killer web apps though, it's vital that you understand the process thoroughly.</div>
      </li>
      <li><span class="headline"><a href="/blog/dev/how-to-debug-in-php/">How to Debug in PHP</a></span>
        <div>Nobody enjoys the process of debugging their code. If you want to build killer web apps though, it's vital that you understand the process thoroughly.</div>
      </li>
    </ul>
  </div>
</div>
<div style="clear:both;"></div>